travis:
  secure:
    BINSTAR_TOKEN: EPKWV7ZEolxgiRvjJ/CuUU3wA32jW373Wss8eYZayWBesdU30RNhL1c4MXY2onNC2j/9y9E9GvuHFxr+nruT/VQ+95Fs7uCk33J451QJoMqvo5BHbGHf+ExVTpU2PQSX/ur0tOWI2Q1wETvZH1CFvAtvXqc+4VtzbFMPLea8KAqzofKToL2NY8SuEpXsugCdo5UHVdaU9RMsVVXiG87fMeCh1gn+oNBLF168AHVithQESDQ188vOe3xDAyHgy5fR1RoHisB729Jo6xi+6tQ7EDXEMMNvesvTdcVL4sQS6IwOeiOOqT84HobunksTEp7WnsKR38ptmyOc3BJBxTZdzWEu4jgaOn05fCAqRmOCByYWUK3sxyF9o45RuLx0m8Fpn7UDgj3V6t9aPSN4vT969Gaekt+SJ2nQgk2q1jsbOHmRjyVE9YeOH4i2ZnaOt6kRFXZD6C6vp5OCR98X+ax2OyodfCKteoYKKaN7+i0g05n7JxVVX0w04ytpjngpqqzStRtWsz/XK8e1vCb1UBRu2etVV3TiHt5y2PaMAc8p4UKLJSNvfrpl7qJTICIn5oI5rDn0zhCM1vC7a3bgxA5VKCWAIy8ZEJAjxF9roeib/H+m6FvY6vjyxeTUHDEBnZAmJleT8xxDfvza+ZGFuQSDxUQTl8iUTKvgWnkMWJ/S0UA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
